# Generated by Django 3.0 on 2023-06-02 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=30)),
                ('Duration_time', models.FloatField()),
                ('song', models.FileField(upload_to='musics/')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 2, 15, 23, 46, 472532))),
            ],
        ),
    ]
