# Generated by Django 3.0 on 2023-06-03 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 3, 16, 28, 1, 713427)),
        ),
    ]
