# Generated by Django 3.0 on 2023-06-22 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230622_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 22, 14, 36, 49, 572765)),
        ),
    ]
