# Generated by Django 3.0 on 2023-06-27 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230627_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 27, 21, 52, 44, 113720)),
        ),
    ]
